- name: Create Foo bar Azure VM
  hosts: localhost
  connection: local
  tasks:
#   - name: Create resource group
#     ignore_errors: yes
#     azure_rm_resourcegroup:
#       name: Infra-as-code-group
#       location: eastus
  - name: Create virtual network
    ignore_errors: yes
    azure_rm_virtualnetwork:
      resource_group: Infra-as-code-group
      name: myVnet
      address_prefixes: "10.0.0.0/16"
  - name: Add subnet
    ignore_errors: yes
    azure_rm_subnet:
      resource_group: Infra-as-code-group
      name: mySubnet
      address_prefix: "10.0.1.0/24"
      virtual_network: myVnet
  - name: Create public IP address
    ignore_errors: yes
    azure_rm_publicipaddress:
      resource_group: Infra-as-code-group
      allocation_method: Static
      name: myPublicIP
    register: output_ip_address
  - name: Dump public IP for VM which will be created
    debug:
      msg: "The public IP is {{ output_ip_address.state.ip_address }}."
  - name: Create Network Security Group that allows SSH
    ignore_errors: yes
    azure_rm_securitygroup:
      resource_group: Infra-as-code-group
      name: myNetworkSecurityGroup
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
  - name: Create virtual network inteface card
    ignore_errors: yes
    azure_rm_networkinterface:
      resource_group: Infra-as-code-group
      name: myNIC
      virtual_network: myVnet
      subnet: mySubnet
      public_ip_name: myPublicIP
      security_group: myNetworkSecurityGroup
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: Infra-as-code-group
      name: myVM
      vm_size: Standard_DS1_v2
      admin_username: azureuser
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/azureuser/.ssh/authorized_keys
          key_data: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC45vTzY8LFjqrFnSVBzO16AgKpVXk0YVheo8RhuGxWechbpcas0Dr220yxmPzM3ugwHRCNkFPrS7juespo5MjuroJPKPRyRw9jjxMNXt2uvFJoYz+FGHb1kBylBUphU0zoeWboJi7dTobHOssk558kC8b6vje3GxFjjftKjDDwQubMMKnUf3wJuuQZ9jOu7qQhMwmqwujGhh2XccPXZSwisDGhbH/nZDln/vaO8MPF/G/kxAH5Kswf0ZVnsp5czVREtUMJHUzDGz6aD6hkoF9BXuVVNSZb3i8O9WjbWe6NB+j7FYb0PFrFEsMGqZChpqOrphXYilHAedxb1fPzTjCR centos@np-dp-mysql-data-01.gs.local'
      network_interfaces: myNIC
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.5'
        version: latest
