- name: Spins for Azure VM
  hosts: localhost
  connection: local
  tasks:
    - name: Power Off
      azure_rm_virtualmachine:
        resource_group: Infra-as-code-group
        name: myVM
        started: no
